### ISSUE TITLE
lz4 library is outdated

### ISSUE THREAD

**Issue by halileohalilei** [tunabrain/sparse-voxel-octrees#12]
So I was having a look at this on an Ubuntu 15.10 machine, and everything was fine till I tried to run the program after building it. When I ran the program, I only got a segmentation fault, so I traced it back to where it was originated from. It seems there is a bug in the lz4 library, which was fixed some time ago. Simply swapping the lz4.h and lz4.c with the updated versions from https://github.com/Cyan4973/lz4 solves the problem. Just wanted to give you a heads up.

**Comment by tunabrain** [comment]
Fixed by #15 . Thanks for reporting this!
