### ISSUE TITLE
Problem while running setupbuild.sh

### ISSUE THREAD

**Issue by prateekchandan** [tunabrain/sparse-voxel-octrees#13]
Hi ,
I am facing issue while running setupbild.sh

This is the error
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find SDL (missing: SDL_LIBRARY SDL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSDL.cmake:176 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:29 (find_package)

**Comment by tunabrain** [comment]
This is an error message coming from the CMake build system. It means that it cannot find the SDL library on your system. Depending on your system, there are different ways of setting up libraries in a way that CMake can find them. On Linux systems, your package manager will usually take care of this. On Windows, things can get a bit more complicated.

This is a general setup question about CMake, and there are good online resources on the topic for most system combinations. I suggest googling the issue for your particular setup.

Thanks!
