### ISSUE TITLE
Running on OSX

### ISSUE THREAD

**Issue by gon** [tunabrain/sparse-voxel-octrees#16]
How do I run this on OSX?

**Comment by andeplane** [comment]
You need the SDL library in addition. One easy way to achieve this is to use [homebrew](http://brew.sh/):
`brew install sdl`
And then it compiles nicely with
```
cmake .
make
./sparse-voxel-octrees -viewer modelsYZRGB-Dragon.oct
```

**Comment by moloned** [comment]
I had to remove the following lines from the CMakeLists.txt to get a makefile that compiled correctly under OSX

https://stackoverflow.com/questions/11032157/sdl-in-xcode-4-3-2-sdlmain-o-undefined-symbols

#if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
#   set(Sources ${Sources} "src/SDLMain.m")
#endif()

**Comment by tunabrain** [comment]
Thanks! I've added build instructions for macOS to the readme.
