### ISSUE TITLE
problems with vs2017

### ISSUE THREAD

**Issue by w33haa** [tunabrain/sparse-voxel-octrees#18]
hello,  `setup_builds.bat`  doesn't seem to work. And i found the param of cmake is wrong.
`cmake ../ -G "Visual Studio 12 Win64`
by using 
`cmake --help`
i found the correct generator name
`cmake ../ -G "Visual Studio 12 2013 Win64`
error:
```
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.
```
then i try 
`cmake ../ -G "Visual Studio 15 2017 Win64`
then the error:
```
CMake Error at CMakeLists.txt:12 (message):
  The compiler d:/Program Files (x86)/Microsoft Visual
  Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
  seems to have no C++11 support.  Please try again with a more recent
  compiler version.
```
cmake file where error occur:
```
if(CXX11_COMPILER)
    enable_cxx11()
else()
    message(FATAL_ERROR "The compiler ${CMAKE_CXX_COMPILER} seems to have no C++11 support. Please try again with a more recent compiler version.")
endif()
```
doesn't vs2017 support cxx11?

**Comment by clojur** [comment]
???,can you speak Chinese?

**Comment by moloned** [comment]
I have updated the repo to support Visual Studio 2017 and SDL 2.0.5 and shared with Benedikt as I can't update the repo directly. Hopefully he can update the main repo

**Comment by tunabrain** [comment]
I've updated the repo with additional build instructions and fixed the scripts/CMake files to work with newer Visual Studio versions.

Thanks!
Benedikt
