### ISSUE TITLE
Segmentation fault on OSX 10.12.5

### ISSUE THREAD

**Issue by zach-babb-moovel** [tunabrain/sparse-voxel-octrees#19]
I am getting Segmentation Fault 11 when trying to run `./sparse-voxel-octrees -viewer ./models/YZRGB-Dragon.oct` on my Mac. On the off chance that someone is still checking this repo and might know what's going on, I'm posting here. It seems to be coming from the renderLoop in Main.cpp.

**Comment by tunabrain** [comment]
I tested this today on macOS Sierra and it seems to build and run fine. I've added macOS build and run directions to the Readme.md that worked on my macbook, in case it helps.

Thanks!
Benedikt
