### ISSUE TITLE
unexpected holes at the boundary of the bounding box

### ISSUE THREAD

**Issue by bitxue** [tunabrain/sparse-voxel-octrees#5]
Hi, Benedikt

In some cases, the program will result in unexpected holes at the boundary of the bounding box. 

![20150201144152](https://cloud.githubusercontent.com/assets/8717601/5991364/885f612a-aa24-11e4-9704-b2075217a1dc.png)
![20150201145946](https://cloud.githubusercontent.com/assets/8717601/5991366/9d15f174-aa24-11e4-9dad-45f0664da338.png)

Use the head model at 2048 resolution to reproduce. The head model can be downloaded here:
http://graphics.cs.williams.edu/data/meshes/head.zip

Best,
Junjie

**Comment by tunabrain** [comment]
Hi Junjie,

Thanks for reporting this. I added a one voxel wide border during rasterization as safety padding. Does the latest commit fix it for you?

**Comment by bitxue** [comment]
Hi, Benedikt

Yeah, it is fixed. Well done!
